batch=128
optimizer='adam'
learning_rate=0.0002
generator_advantage=200

[config]
n_z=100
image_shape=[64, 64, 3]

[config_critic]
mode='cnn'
parameter={batch_norm=true, batch_norm_decay=0.9}

[config_generator]
mode='cnn'
parameter={batch_norm=true, batch_norm_decay=0.9}

