gradient_clip=0.01
down_scale = 1
batch=64
optimizer='adam'
learning_rate=0.00005
n_critic=5

[config]
n_z=100
image_shape=[128, 128, 3]

[config_critic]
mode='cnn'
parameter={batch_norm=true, batch_norm_decay=0.9}

[config_generator]
mode='cnn'
parameter={batch_norm=true, batch_norm_decay=0.9}

