gradient_clip=0.000001
batch=64
optimizer='adam'

[config]
n_z=128
image_shape=[128, 128, 3]

[config_critic]
mode='cnn'
parameter={batch_norm=true, batch_norm_decay=0.999}

[config_generator]
mode='cnn'
parameter={batch_norm=true, batch_norm_decay=0.999}

