gradient_clip=0.00001
batch=128
optimizer='adam'
down_scale=1
learning_rate=0.00001
n_critic=5

[config]
n_z=128
image_shape=[128, 128, 3]

[config_critic]
mode='cnn'
parameter={batch_norm=true, batch_norm_decay=0.999}

[config_generator]
mode='cnn'
parameter={batch_norm=true, batch_norm_decay=0.999}

