gradient_clip=0.05
#gradient_penalty=10

batch=64
optimizer='rmsprop'
learning_rate=0.00005
n_critic=5
initializer='truncated_normal'
overdose=true

[config]
n_z=100
image_shape=[64, 64, 3]

[config_critic]
mode='cnn'
parameter={batch_norm=true, batch_norm_decay=0.99, batch_norm_scale=true}

[config_generator]
mode='cnn'
parameter={batch_norm=true, batch_norm_decay=0.99, batch_norm_scale=true}
